Refactor - version 2
matchms/matchms pull request #139
Opened 2020-08-26 15:00 UTC by florian-huber

2020-09-08 07:08 UTC, florian-huber commented
Sorry to send this big PR your way @sverhoeven. Here I implemented similarity functions that inherit from ``BaseSimilarityFunction`` and that only return numpy arrays as scores (so no ``Scores`` objects). But I would be definitely open to discuss alternatives!

2020-09-08 15:11 UTC, sverhoeven requested changes
That is a lot of changes. Nice work to testing and documenting everything and keep the code coverage up.

* see suggestions in inlined conversations
* Missing is a Change and Deprecated section in the CHANGELOG 
* Having a class ending with `Function` makes it a bit awkward to talk about it. Could we rename `BaseSimilarityFunction` to `BaseSimilarity` or `BaseSpectrumSimilarity`?

2020-09-08 18:08 UTC, florian-huber commented on matchms/similarity/FingerprintSimilarity.py
>      jaccard_similarity_matrix
Good idea, thanks!

2020-09-08 18:11 UTC, florian-huber commented on matchms/similarity/CosineGreedy.py
> +        score, n_matches = cosine_greedy.pair(spectrum_1, spectrum_2)
True, done.

2020-09-08 18:13 UTC, florian-huber commented on matchms/similarity/BaseSimilarityFunction.py
> +        """Required: Method to calculate the similarity for one input pair.
Looks nicer. Thanks.

2020-09-08 18:18 UTC, florian-huber commented on matchms/similarity/__init__.py
> +  (:meth:`~matchms.similarity.FingerprintSimilarity`)
Thanks. Done.

2020-09-08 18:37 UTC, florian-huber commented on matchms/similarity/BaseSimilarityFunction.py
> +    is_commutative = True
Good point, thanks! Done.

2020-09-08 18:37 UTC, florian-huber commented on matchms/similarity/BaseSimilarityFunction.py
> +            if is_symmetric:
Thanks! Done.

2020-09-08 18:38 UTC, florian-huber commented on matchms/similarity/CosineGreedy.py
> +    :meth:`~matchms.similarity.CosineHungarian`). In practice this will rarely
Done

2020-09-08 18:39 UTC, florian-huber commented on matchms/similarity/CosineHungarian.py
> +    :meth:`~matchms.similarity.CosineGreedy`, but does represent a mathematically proper
Done.

2020-09-09 08:05 UTC, florian-huber commented on matchms/Scores.py
> +        self.queries = numpy.asarray(queries)
Thank you!

2020-09-09 08:10 UTC, florian-huber commented on matchms/Scores.py
>              Function which accepts a reference + query object and returns a score or tuple of scores
I changed the docstring and linked to ``BaseSimilarity``.

2020-09-09 08:19 UTC, florian-huber commented on matchms/similarity/FingerprintSimilarity.py
> +    Code example:
Yay! :)

2020-09-09 08:23 UTC, florian-huber commented on matchms/Scores.py
> -        assert callable(similarity_function), "Expected input argument 'similarity_function' to be callable."
That gives a pylint complaint:
``pylint: isinstance-second-argument-not-valid-type / Second argument of isinstance is not a type``

2020-09-09 10:53 UTC, florian-huber commented on matchms/Scores.py
> +        # pylint: disable=too-many-arguments
Still complained when I removed it.

2020-09-09 10:53 UTC, florian-huber commented on matchms/Scores.py
> -        assert callable(similarity_function), "Expected input argument 'similarity_function' to be callable."
Done.

2020-09-09 10:54 UTC, florian-huber commented
Thanks a lot for the review Stefan!
I now changed ``BaseSimilarityFunction`` to ``BaseSimilarity`` and added changes to the Changelog.

2020-09-09 14:48 UTC, sverhoeven commented on matchms/Scores.py
> +        # pylint: disable=too-many-arguments
ok

2020-09-09 15:01 UTC, sverhoeven requested changes
Almost there, whats there looks good.

However some files not-changed by PR still need updating:
* [calculate_scores()](https://github.com/matchms/matchms/blob/refactor_v2/matchms/calculate_scores.py#L9) 
  * still has old type for similarity function, it should be matchms.similarity.BaseSimilarity.BaseSimilarity
  *  method needs `is_symmetric` argument, so Scores.calculate can be deprecated without losing functionality.
* please remove SimilarityFunction from matchms/typing.py to avoid confusion

2020-09-10 07:21 UTC, florian-huber commented
Thanks a lot @sverhoeven . I removed the old typing and added ``is_symmetric`` to ``calculate_scores()``.

2020-09-10 07:52 UTC, sverhoeven approved these changes
Everything is order, ready to merge

2020-09-10 13:20 UTC, florian-huber commented
Thanks a lot Stefan to help with this beast :)

2020-09-10 13:21 UTC, merged