Refactor environment
matchms/matchms pull request #145
Opened 2020-09-10 07:44 UTC by florian-huber

2020-09-10 11:06 UTC, sverhoeven requested changes
Developer install and tests work with py3.8
Conda build works with py3.7 conda env without upgrading to py38, as expected

Can you add 3.8 to setup.py, so supported versions are mentioned everywhere?

To reduce number of CI jobs run python versions only one ubuntu and run 3.8 on Windows and OSX.

2020-09-10 11:30 UTC, florian-huber commented on readthedocs/index.rst
> +- Python 3.7 or 3.8
Good point, done.

2020-09-10 12:53 UTC, florian-huber commented
Many thanks @sverhoeven . 
I did add the change to setup.py.
And I also changed my push vs pull_request solution to the one you suggested by mail. (I had missed that any merged PR will anyway trigger a ``push`` so we do not need to take care of that)

2020-09-11 07:37 UTC, sverhoeven approved these changes

2020-09-11 10:47 UTC, florian-huber commented
Thanks again Stefan for the reviewing!

2020-09-11 10:47 UTC, merged