refactor CI workflow
matchms/matchms pull request #167
Opened 2021-01-04 15:02 UTC by florian-huber

2021-01-26 08:48 UTC, sverhoeven requested changes
Job graph looks good. Will definitely speed up, by catching most common mistakes in first job.

The tests requiring rdkit (`tests/test_utils.py`) are not tested. Could you add a pytest to `anaconda_dev` job. 

Also the SonarCloud analysis will miss the coverage of those tests. To get a bit higher coverage you could run the analysis in the `anaconda_dev` job. As coverage is already high I don't think it is absolutely needed.

2021-01-26 08:48 UTC, sverhoeven commented on .github/workflows/CI_build.yml
> +    name: Pypi and documentation build / python-${{ matrix.python-version }} / ${{ matrix.os }}
Documentation is not tested here
```suggestion
    name: Pypi / python-${{ matrix.python-version }} / ${{ matrix.os }}
```

2021-01-26 08:48 UTC, sverhoeven commented on .github/workflows/CI_build.yml
> +        if: matrix.os == 'ubuntu-latest'
No matrix in job so this line can be removed.
```suggestion
```

2021-01-29 11:00 UTC, florian-huber commented
Thanks Stefan, good point. I to hastily adapted the `Spec2Vec` refactored workflow for this here and then missed the `rdkit` issue.
I now added another test and sonarcloud run to the `anaconda_dev` run.

2021-01-29 12:10 UTC, sverhoeven approved these changes

2021-01-29 12:13 UTC, florian-huber commented
Thanks a lot for reviewing Stefan!

2021-01-29 12:13 UTC, merged