Load all file types
matchms/matchms pull request #396
Opened 2023-04-12 08:52 UTC by niekdejonge

Added a function to infer filetype when loading in functions. 

For most other tools using Matchms a function is needed that just uses the extension to assume file type. This has now been added. 

@florian-huber @hechth Do you agree with this implementation?

2023-04-14 12:28 UTC, hechth requested changes
I think this is a cool feature to have a central loading function - maybe we can add the extension as an optional parameter? Galaxy for example renames everything as .dat and then you can get the filetype from the metadata, I think some databases might work in a similar fashion - so this would greatly improve usability and only add a little bit of complexity.

2023-04-19 06:48 UTC, hechth commented
@niekdejonge I made some small updates to your PR that contains the changes I mentioned - please let me know if you agree with those :)

@florian-huber otherwise I think this is good and can be merged. We could also some point implement a wrapper around the export process.

2023-04-19 09:09 UTC, niekdejonge commented
@hechth Sorry for the later reply! Thanks a lot for already implementing the changes, I will check them now.

2023-04-19 09:10 UTC, niekdejonge commented on matchms/importing/__init__.py
> +    "load_spectra",
I was afraid this might cause some circular import issues, but if the tests pass that is a good addition indeed!

2023-04-19 09:11 UTC, niekdejonge commented on tests/test_load_spectra.py
> +@pytest.mark.parametrize("filename, ftype, expected_num_spectra", [
Great that is a lot cleaner!

2023-04-19 09:12 UTC, niekdejonge commented on matchms/importing/load_spectra.py
> +    if ftype is None:
Good addition!

2023-04-19 09:14 UTC, niekdejonge commented
@florian-huber @hechth Thanks Helge, good suggestions! I will merge the pull request.

2023-04-19 09:15 UTC, merged