Add import and export functions for json files
matchms/matchms pull request #52
Opened 2020-05-27 15:23 UTC by florian-huber

2020-06-02 14:00 UTC, sverhoeven requested changes

2020-06-02 15:06 UTC, florian-huber commented on matchms/exporting/save_as_json.py
> +        fout.write("]")
Nice Stefan. Looks much better your way.

2020-06-02 15:14 UTC, florian-huber commented on matchms/importing/load_from_json.py
> +    return spectrums
Looking good, thanks! We might also add our own example in addition to the GNPS ones as a separate link.

2020-06-02 15:15 UTC, florian-huber commented on tests/test_save_as_json_load_from_json.py
> +        assert spectrum_imports[1] == spectrum2, "Original and saved+loaded spectrum not identical"
Good point. Thanks.

2020-06-02 17:30 UTC, florian-huber commented
@sverhoeven Somehow redefining the json.JSONEncoder default function clashes with pylint. See also here: https://github.com/PyCQA/pylint/issues/1631
Commenting  to ignore didn't work for me so far.

2020-06-03 07:41 UTC, sverhoeven commented
Seems pylint is OK again.

@florian-huber could you merge master into this branch and add an entry to the changelog?

2020-06-03 07:55 UTC, florian-huber commented
Thanks @sverhoeven . Yes, I'll merge master and (hopefully) complete it this afternoon.

2020-06-03 14:42 UTC, florian-huber commented on tests/test_save_as_json_load_from_json.py
> +def test_save_and_load_json_single_spectrum():
I remember that I tried that (with Juriaan I think) but then we ran into pylint issues I believe. I can try again if it works now.

2020-06-03 15:00 UTC, florian-huber commented on tests/test_save_as_json_load_from_json.py
> +def test_save_and_load_json_single_spectrum():
Seems to work now, so I changed the tests to ``tmp_path``.

2020-06-03 17:01 UTC, sverhoeven requested changes
Looking good, some small changes requested though

2020-06-04 14:36 UTC, florian-huber commented on tests/test_save_as_json_load_from_json.py
> +    # with tempfile.TemporaryDirectory() as d:
missed that one, thanks.

2020-06-04 14:37 UTC, florian-huber commented on tests/test_save_as_json_load_from_json.py
> +    assert len(spectrum_imports) == 0, "Spectrum without peaks should be skipped"
Thanks. That seems a good addition indeed.

2020-06-04 14:39 UTC, sverhoeven approved these changes

2020-06-05 06:07 UTC, florian-huber commented
Thanks for the review @sverhoeven !

2020-06-05 06:07 UTC, merged